// <auto-generated />
namespace MyInterviewQuestions.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Set_User_Required_UserName_PasswordHash_PasswordSalt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_User_Required_UserName_PasswordHash_PasswordSalt));
        
        string IMigrationMetadata.Id
        {
            get { return "201808010809281_Set_User_Required_UserName_PasswordHash_PasswordSalt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
